[workspace]
authors = ["Emanuele Giacomini <giacomini@diag.uniroma1.it>"]
channels = ["robostack-humble", "conda-forge"]
name = "multiplatform_ros2_builder"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
ros-humble-ament-cmake-auto = ">=1.3.12,<2"
compilers = ">=1.11.0,<2"
pkg-config = ">=0.29.2,<0.30"
cmake = ">=4.1.1,<5"
ninja = ">=1.13.1,<2"
eigen = ">=3.4.0,<4"
ros-humble-nav2-map-server = ">=1.1.18,<2"
ros-humble-ament-package = ">=0.14.1,<0.15"
opencv = ">=4.11.0,<5"
ros-humble-tf2-tools = ">=0.25.14,<0.26"

[activation]
scripts = ["install/setup.sh"]

[activation.env]
CYCLONEDDS_URI = "file://${PIXI_PROJECT_ROOT}/cyclonedds.xml"
FASTRTPS_DEFAULT_PROFILES_FILE = "${PIXI_PROJECT_ROOT}/fastdds.xml"
